// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://google.com",
        "contact": {
            "name": "Tardelli Moura",
            "url": "https://google.com",
            "email": "tardelli.m@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Responds running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthZ"
                ],
                "summary": "healthz",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/pokemon": {
            "get": {
                "description": "Get all pokemons in database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pokemon"
                ],
                "summary": "Get all pokemons in database",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.PokemonRequest"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Find pokemon by name and save in database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Pokemon"
                ],
                "summary": "Find pokemon by name and save in database",
                "parameters": [
                    {
                        "description": "Operations JSON",
                        "name": "operations",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.PokemonRequest"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.PokemonRequest"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.PokemonRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Pokemon GO lang",
	Description:      "Example of ports and adapters architecture with Golang.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
